#!/bin/sh

mountable=$(lsblk -lp | grep -v "/dev/sda" | grep "part $\|disk $" | awk '{print $1 " ("$4" / "$6")"}')
[[ "$mountable" = "" ]] && exit 0
choosen=$(echo "$mountable" | dmenu -i -p 'Hangi Diski Bağla?' | awk '{print $1}')
[[ "$choosen" = "" ]] && exit 0
sudo mount $choosen && exit 0
dirs=$(find /mnt /media /mount /home -type d -maxdepth 3 2>/dev/null | tail -n +2)
mountpoint=$(echo "$dirs" | dmenu -i -p 'Diski nereye Bağla?' )
[[ "$mountpoint" = "" ]] && exit 0
if [[ ! -d "$mountpoint" ]]; then
    shouldmkdir=$(printf 'Evet\nHayır' | dmenu -i -p 'Böyle birşey yok. Oluştur?' )
    [[ "$shouldmkdir" = "Hayır" ]] && exit 0
    sudo mkdir -p "$mountpoint"
fi
sudo mount $choosen $mountpoint 
echo $mountpoint
sudo chown ahmedselim:ahmedselim -R $mountpoint
sudo chmod 700 -R $mountpoint
