#!/bin/sh

search_github(){
    result=$(cat ~/dsearch/github | dmenu -sb '#f5f5f5' -sf '#333' -nb '#333' -i -p 'Hangi Sayfa? ' )
    [[ "$result" = "" ]] && exit 0
    grep -q "$result" ~/dsearch/github;
    if [[ $? != 0 ]]; then
        echo "$result" >> ~/dsearch/github
    fi

    firefox --new-tab "https://github.com/search?q=$(echo $result | awk '{for(i=1;i<=NF;i++)printf $i"+"}' | iconv -f utf-8 -t ascii//TRANSLIT )"
}

search_stackoverflow(){
    result=$(cat ~/dsearch/stackoverflow | dmenu -sb '#f48024'  -nb '#333' -i -p 'Hangi Sayfa? ' )
    [[ "$result" = "" ]] && exit 0
    grep -q "$result" ~/dsearch/stackoverflow;
    if [[ $? != 0 ]]; then
        echo "$result" >> ~/dsearch/stackoverflow
    fi

    firefox --new-tab "https://stackoverflow.com/search?q=$(echo $result | awk '{for(i=1;i<=NF;i++)printf $i"+"}' | iconv -f utf-8 -t ascii//TRANSLIT )"
}


search_youtube(){
    result=$(cat ~/dsearch/youtube | dmenu -sb '#FF0000' -nb '#333' -i -p 'Hangi Video? ' )
    [[ "$result" = "" ]] && exit 0
    grep -q "$result" ~/dsearch/youtube; 
    if [[ $? != 0 ]]; then
        echo "$result" >> ~/dsearch/youtube
    fi

    firefox --new-tab "https://www.youtube.com/results?search_query=$(echo $result | awk '{for(i=1;i<=NF;i++)printf $i"+"}' | iconv -f utf-8 -t ascii//TRANSLIT )"
}

search_google(){
    result=$(cat ~/dsearch/google | dmenu -sb '#0F9D58' -nb '#333' -i -p 'Hangi Sayfa? ' )
    [[ "$result" = "" ]] && exit 0
    grep -q "$result" ~/dsearch/google;
    if [[ $? != 0 ]]; then
        echo "$result" >> ~/dsearch/google
    fi

    firefox --new-tab "https://www.google.com/search?q=$(echo $result | awk '{for(i=1;i<=NF;i++)printf $i"+"}' | iconv -f utf-8 -t ascii//TRANSLIT )"
}

choose(){
    result=$(printf "Github\nStackoverflow\nGoogle\nYoutube" | dmenu -i -p 'Hangisinde Aramak İstersin? ')
    echo "$result"
}

case $(choose) in
    Github) search_github ;;
    Stackoverflow) search_stackoverflow ;;
    Youtube) search_youtube ;;
    Google) search_google ;;
esac
