#!/bin/sh

response=$(printf 'Geri\nKapat\nYeniden Başlat' | dmenu -i -p 'Ne Yapmak İstiyorsun? ')

case $response in
    'Geri') echo exit 0;;
    'Kapat') echo

        [[ $(printf 'Hayır\nEvet' | dmenu -sb '#f07178' -nb '#BE5046' -nf '#292d3e' -i -p 'Emin Misin? Kapatacak Bak ') == Evet ]] && sudo shutdown now;;
    'Yeniden Başlat')
        [[ $(printf 'Hayır\nEvet' | dmenu -sb '#f07178' -nb '#BE5046' -nf '#292d3e' -i -p 'Emin Misin? Kapatacak Bak ') == Evet ]] && sudo shutdown -r now;;
esac
