#!/bin/sh

response=$(printf 'Geri\nKapat\nYeniden Başlat' | dmenu -i -p 'Ne Yapmak İstiyorsun? ')

case $response in
    'Geri') echo exit 0;;
    'Kapat') echo 
        [[ $(printf 'Hayır\nEvet' | dmenu -i -p 'Emin Misin? Kapatacak Bak ') == Evet ]] && sudo shutdown now;;
    'Yeniden Başlat') 
        [[ $(printf 'Hayır\nEvet' | dmenu -i -p 'Emin Misin? Yeniden Başlatacak Bak ') == Evet ]] && sudo shutdown -r now;;
esac
