#!/bin/sh

unmountable=$(lsblk -lp | grep -v "part $\|disk $\|/dev/sda\|NAME" | awk '{print $1 " ("$4" / "$6")"}')
[[ "$unmountable" = "" ]] && exit 0
choosen=$(echo "$unmountable" | dmenu -i -p 'Hangi Diski Çıkar?' | awk '{print $1}')
[[ "$choosen" = "" ]] && exit 0
isunmounted=$(sudo umount $choosen 2>&1 && rootify "Bağlantı Kesildi" "$choosen diskinin bağlantısı kesildi")
[[ "$isunmounted" = "" ]] && exit 0
shouldforce=$(printf "Hayır\nEvet" | dmenu -i -p 'Disk şuanda meşgul. Yinede çıkar?')
[[ "$shouldforce" != "Evet" ]] && exit 0
sudo umount -l $choosen && rootify "Bağlantı Kesildi"  "$choosen diskinin bağlantısı kesildi"
