#!/bin/sh


[ -f "$1" ] && cp "$1" ~/.config/wallpaper

[ -d "$1" ] && cp "$(find "$1" -type f -name '*.jpg' -o -name '*.jpeg' -o -name '*.png' | shuf -n 1)" ~/.config/wallpaper


xwallpaper --zoom ~/.config/wallpaper
